### ISSUE TITLE
dict_to_fig function?

### ISSUE THREAD

**Issue by divyanshu16** [mpld3/mpld3#468]
I have a figure of type matplotlib.figure.Figure

I want to store it in JSON so that I can pull it back later to convert back to matplotlib.figure.Figure  

I can see the fig_to_dict function offered by the mpld3 but can't see any function which reverts back to matplotlib figure. Is there  dict_to_fig function too? I couldn't find any similar function.

**Comment by cliffckerr** [comment]
Hi @divyanshu16 -- unfortunately you can't restore a figure from a JSON, because figure objects use things that can't be stored in JSON (e.g., weak references). However, you can use `saveobj()` from the `sciris` library (https://github.com/sciris/sciris, or `pip install sciris):

```
import sciris as sc
import matplotlib.pyplot as plt

fig1 = plt.plot([1,2,3],[2,4,7])
sc.saveobj('fig.obj', fig1)

plt.close()

fig2 = sc.loadobj('fig.obj')
plt.show()
```

Under the hood this is just using the `pickle` module, so you can use that too.

**Comment by vladh** [comment]
Closing, feel free to add another comment if you still need help with this.
