### ISSUE TITLE
Need for a plugin like mpld3.plugins.EdgeLabelTooltip for being able to highlight an edge between two nodes

### ISSUE THREAD

**Issue by hbalp** [mpld3/mpld3#486]
The main idea is to be able to highlight the edges of a graph when moving the mouse on it.
The same kind of need has already been formalized by @Patrik in stackoverflow.
[https://stackoverflow.com/questions/65044559/how-to-get-a-tooltip-for-an-edge-of-an-networkx-graph-using-mpld3-tooltip](url)

**Comment by vladh** [comment]
Hi @hbalp,

I understand you need a plugin to help you with what you're trying to build. Unfortunately, this is not something I can do for you, but I can refer you to the plugin documentation, and some plugin examples, so that you can build it on your own!

https://mpld3.github.io/_downloads/custom_plugins.html

https://mpld3.github.io/examples/custom_plugin.html#custom-plugin

https://mpld3.github.io/examples/random_walk.html#random-walk
