### ISSUE TITLE
How to sponsor mpld3 dev ?

### ISSUE THREAD

**Issue by arita37** [mpld3/mpld3#499]
There is Github Sponsor :
https://github.com/sponsors

Would like to know how to sponsor the development of mpld3 ?
It's nice and very efficient application,

**Comment by vladh** [comment]
Hey @arita37,

Thank you very much for the offer! I'm glad you enjoy mpld3.

I'm the current maintainer of mpld3 but, as you may have noticed, I don't generally dedicate quite as much time as I would like to to maintaining the library. Therefore, I don't think it would be right to accept donations.

If you are able to contribute with your time, there are a few beginner-friendly issues. Otherwise, knowing that mpld3 was helpful to you is already very nice, so thank you for your comment!

**Comment by arita37** [comment]
Thanks.
But, am over busy by hundred things…
So thats why am looking to sponsor
for some improvement devs.
