### ISSUE TITLE
pandas dataframes all look CSS formatted, can't undo

### ISSUE THREAD

**Issue by rayanelhelou** [mpld3/mpld3#510]
After trying [the HTML tooltip demo linked here](https://mpld3.github.io/examples/html_tooltips.html), all my pandas dataframes now look black and gray like the tooltip. I tried closing JupyterLab and resarting, didn't work. Now all my dataframes look bad. Can you help, please?

**Comment by vladh** [comment]
I unfortunately don't quite understand what the problem is. There's no real way for me to research this if all the information I have is "the dataframes look bad".

Could you please research the issue a bit more, maybe provide some screenshots of what's happening, and maybe try to figure out if the problems occurs in some situations and not others? If you describe the issue more precisely and help me reproduce it, I can absolutely have a look. Not everyone uses JupyterLab (I don't), and it would be good to rule it out as a cause, so I would suggest trying to make a Python-only reproduction.

**Comment by bryevdv** [comment]
Pandas only renders HTML in notebook contexts. In any case, from a glance at the plugin example the issue is clearly CSS pollution.

**Comment by rayanelhelou** [comment]
Thanks for the suggestion. The "CSS pollution" is what I think it was. The problem is solved.
